---
- name: Deploy twitter scraping code
  become: yes
  hosts: all
  vars:
    bindir: /usr/local/bin
    datadir: /usr/local/share
  tasks:
    - name: Create app user
      user:
        name: mfa
        create_home: no
        shell: /bin/bash
        system: yes

    - name: Create lockfile for systemd services
      file:
        name: /var/lock/mfa
        owner: mfa
        state: touch
        mode: u=rw,g=r,o=r

    - name: Copy and extract release tarball
      unarchive:
        dest: /usr/local/
        src: mfa-{{ version }}.tar.zst
        owner: root
        group: root

    - name: Bootstrap postgres database
      become_user: dev
      shell: "{{ bindir }}/bootstrap.sh -h '' -u dev -d db -a {{ datadir }}/mfa/accounts.csv -s {{ datadir }}/mfa/sql"

    - name: Start systemd services
      systemd:
        daemon_reload: yes
        name: "{{ item }}.timer"
        enabled: yes
        state: started
      loop:
        - profile
        - scan
        - timeline
