name: Release builder
on:
  push:
    branches: [ production ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set tag name
        id: set_tag
        run: echo "::set-output name=tag_name::$(echo $(date +'%Y-%m-%d')-$(head -c 6 <<< ${{ github.sha }}))"

      - name: Install make
        run: sudo apt-get install make

      - name: Build release tarball
        run: make version=${{ steps.set_tag.outputs.tag_name }} build

      - name: Create a new release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.set_tag.outputs.tag_name }}
          files: mfa-${{ steps.set_tag.outputs.tag_name }}.tar.zst
